
//Array de exemplo para demonstrar methods do array
const arr = [1, 2, 3, 4, 5];

arr.push(6)
arr.pop()
arr.shift()
arr.unshift(0)
arr.concat([6, 7])
arr.slice(1, 3)
arr.splice(1, 2)
arr.reverse()
arr.sort()
arr.indexOf(4)
arr.includes(3)
arr.find(x => x > 3)
arr.filter(x => x > 3)
arr.map(x => x * 2)
arr.reduce((sum, x) => sum + x, 0)
arr.join('-')
arr.every(x => x > 2)
arr.some(x => x > 4)
arr.findIndex(x => x > 4)
arr.fill(9)
arr.copyWithin(0, 1)
arr.flatMap(x => [x, x * 2])
arr.entries()
arr.keys()
arr.values()